project:
  type: website

website:
  title: "AI 工具导航"
  navbar:
    left:
      - text: 首页
        href: index.qmd
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
